[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcunet-project"
version = "0.1.0"
description = "MCUNet analysis, optimization, and STM32 deployment toolkit"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "torch",
  "torchvision",
  "numpy",
  "onnx",
  "onnxruntime",
  "tensorflow",
  "onnx-tf",
  "pyserial"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
